using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Sql;
using System.Data.SqlClient;


namespace Practica
{
    public partial class Evidenta : Form
    {
        SqlConnection con = new SqlConnection(Properties.Settings.Default.NetRom_Practica5ConnectionString);
        

        SqlCommand cmd;

        public Evidenta()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            var s = Properties.Settings.Default.NetRom_Practica5ConnectionString;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            StudentForm stud = new StudentForm();
            stud.Show();

           
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Events ev = new Events();
            ev.Show();
        }

        private void Evidenta_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'evidentaDataSet.Evidenta' table. You can move, or remove it, as needed.
          //  this.evidentaTableAdapter.Fill(this.evidentaDataSet.Evidenta);

        }

        internal static void show()
        {
            throw new NotImplementedException();
        }

       
        private void simpleButton4_Click(object sender, EventArgs e)
        {
         
          

        }
    }
}
